### ISSUE TITLE
exon number and the related transcript

### ISSUE THREAD

**Issue by Aufiero** [xiaofengsong/CircAST#2]
Hi,

Thanks for the great tool. 

I run the analysis using your tool but in the results, I do not have the exon number and the related transcript. Is there a way to retrieve which are the exons included in the circRNAs?
I see that I have the exon size and exon offsets. Could you explain what you mean for exonOffsets? 
Thanks

Best,
Simona

**Comment by Aufiero** [comment]
Hi, 

I actually found out what exon offsets are. It should be the difference between the start of exon and the start of the first exon. To get the exon number some calculation is required. It would be great if you could include directly the exon number in the results table with the corresponding transcript.

Thanks.
S

**Comment by zhaodoctor** [comment]
Dear Simona,

The 1st, 2nd, 3rd, 7th, 8th, and 9th columns in the result table are chromosome, start of circular RNA, end of circular RNA, exon number, exon length, and exon offsets, respectively. With these six columns, you can determine the exons included in the circular transcript and calculate each exon’s location.
For example,
 if a circular transcript in the result table has column 1-9 like
                     'chr2 68307041 68314603 circStk39-3-1 Stk39 - 3 68,30,123 0,7323,7440'.
It means this circular transcript is located in ch2 and start from 68307041 to 68314603, which contains 3 exons of length 68, 30, and123. With the offsets, the exons' locations can be calcualted.
The 1st exon locates in 68307041-68307108 (68307041+0=68307041, 68307041+68-1=68307108),
the 2nd locates in 68314364-68314393 (68307041+7323=68314364, 68314364+30-1=68314393),
the 3rd locates in 68314481-68314603 (68307041+7440=68314481, 68314481+123-1=68314603).

Hopefully this will be helpful to you.
Tanks for your suggestion, we will consider it.
JingWu, JianZhao
